// Parity: the TypeScript live engine must reproduce the Python classical core within tolerance, so the
// browser's "live" forecasts are the same computation the offline pipeline does. Fixture is generated by
// scripts/gen_parity_fixture.py (regenerate + recommit when the engine changes).
import { describe, expect, it } from 'vitest';
import fixture from '../lib/__fixtures__/parity.json';
import { CLASSICAL_METHODS, normalPpf } from '../lib/liveEngine';

const byName = Object.fromEntries(CLASSICAL_METHODS.map((m) => [m.name, m.fn]));

describe('TS live engine matches the Python classical core', () => {
  it('normal quantile matches', () => {
    for (const [p, expected] of Object.entries(fixture.normal_ppf)) {
      expect(normalPpf(Number(p))).toBeCloseTo(expected as number, 4);
    }
  });

  for (const c of fixture.cases) {
    it(`case ${c.kind} (n=${c.n}, m=${c.m}, h=${c.h})`, () => {
      for (const m of c.methods) {
        const fit = byName[m.name](c.y as number[], c.m, c.h);
        expect(fit.point.length).toBe(c.h);
        // point path parity
        for (let i = 0; i < c.h; i++) {
          expect(fit.point[i]).toBeCloseTo((m.point as number[])[i], 2);
        }
        // one-step sigma parity
        expect(fit.sigma).toBeCloseTo(m.sigma as number, 3);
      }
    });
  }
});
